tasks:
    goland:
        name: Setup GoLand
        command: |
            echo "Setting up GoLand..."
            # Install JetBrains Gateway dependencies
            sudo apt-get update && sudo apt-get install -y \
                libxtst6 \
                libxrender1 \
                libfontconfig1 \
                libxi6 \
                libgtk-3-0

            # Install Go tools
            go install golang.org/x/tools/gopls@latest
            go install github.com/go-delve/delve/cmd/dlv@latest
            go install github.com/fatih/gomodifytags@latest
            go install github.com/cweill/gotests/gotests@latest
            go install github.com/haya14busa/goplay/cmd/goplay@latest
            go install github.com/josharian/impl@latest
            
            # Print instructions for connecting via Gateway
            echo "To use GoLand:"
            echo "1. Download JetBrains Gateway from https://www.jetbrains.com/remote-development/gateway/"
            echo "2. In Gateway, select 'Connect to Gitpod'"
            echo "3. Use your Gitpod workspace URL"
            echo "4. Sign in with your JetBrains account to activate your license"
        triggeredBy:
            - postEnvironmentStart

services:
    goland:
        name: GoLand
        description: GoLand IDE service
        commands:
            start: |
                echo "Starting GoLand service..."
                # Replace with your GoLand startup command
                # Typically GoLand is started through the IDE itself
                # This is more for setting up necessary tooling
                go mod download
                go mod tidy
            ready: |
                # Basic health check for Go development environment
                if command -v gopls >/dev/null 2>&1 && command -v dlv >/dev/null 2>&1; then
                    echo "GoLand environment is ready"
                    exit 0
                else
                    echo "GoLand environment is not ready"
                    exit 1
                fi
            stop: |
                echo "Stopping GoLand service..."
                # Usually not needed as GoLand is managed by the IDE
                # But you can add cleanup commands here if needed
        triggeredBy:
            - postEnvironmentStart