tasks:
    goland:
        name: Setup GoLand
        command: |
            echo "Setting up GoLand..."
            # Install any necessary Go tools
            go install golang.org/x/tools/gopls@latest
            go install github.com/go-delve/delve/cmd/dlv@latest
        triggeredBy:
            - manual
            - postEnvironmentStart

services:
    goland:
        name: GoLand
        description: GoLand IDE service
        commands:
            start: |
                echo "Starting GoLand service..."
                # Replace with your GoLand startup command
                # Typically GoLand is started through the IDE itself
                # This is more for setting up necessary tooling
                go mod download
                go mod tidy
            ready: |
                # Basic health check for Go development environment
                if command -v gopls >/dev/null 2>&1 && command -v dlv >/dev/null 2>&1; then
                    echo "GoLand environment is ready"
                    exit 0
                else
                    echo "GoLand environment is not ready"
                    exit 1
                fi
            stop: |
                echo "Stopping GoLand service..."
                # Usually not needed as GoLand is managed by the IDE
                # But you can add cleanup commands here if needed
        triggeredBy:
            - postEnvironmentStart